module.exports={
    name:"customerExecutives",
    schema:{
        "name":"String",
        "email":"String",
        "password":"String",
        "type":"String",
        "createdAt":"Date",
        "adminId":"ObjectId",
        "companyName":"String",
        "employeeId":"String"
    }
}