module.exports={
    name:"submissions",
    schema:{
        "userDetails":"Object",
        "submissions":Array,
        "createdAt":"Date",
        "ratings":Number,
        "feedback":String
    }   
}