module.exports={
    name:"user",
    schema:{
        "companyName":"String",
        "email":"String",
        "password":"String",
        "role":"String",
        "createdAt":"Date",
        "userInformation":"Object"  
    }
}